### ISSUE TITLE
[feature request] additional weather variables

### ISSUE THREAD

**Issue by hundredfire** [rkosegi/open-meteo-exporter#53]
Thank you for your work. Openweathermap's 2.5 API getting deprecated in the coming weeks, I expect this nice exporter to get more attention.
I'd like to add more weather variables in the exporter (such as precipitation probability and weather code), but wouldn't know where to start (I'm not familiar with coding, although I'd like to learn someday). Would you be able to point me in the right direction?
Thanks again for the good work, 
Cheers from France

**Comment by rkosegi** [comment]
Hi @hundredfire,
thank you for your interest in this exporter. To add more variables, you have to do more then just add something. Currently there is just `current_weather=true` in the URL which gets you back some default metrics in response body under `current_weather` structure.

By playing with [docs](https://open-meteo.com/en/docs) you will find that response to custom attributes come under different key `current`, so in order to add something, you will have to:

- list all metrics in [URL](https://github.com/rkosegi/open-meteo-exporter/blob/82a115e5cd1eb26f4fb1b41763a900cc6adf02d6/exporter.go#L92)
- modify response [body declaration](https://github.com/rkosegi/open-meteo-exporter/blob/82a115e5cd1eb26f4fb1b41763a900cc6adf02d6/model.go#L40) to use `current` key instead of `current_weather`

I can have a look at it later this week

**Comment by rkosegi** [comment]
with `v1.0.5`, just add `method: alt` to your config file
